---
# tasks file for awscli

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - awscli

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags:
    - awscli

- name: Install awscli
  pip:
    name: awscli
    version: "{{ awscli_version }}"
  tags:
    - awscli

- name: Ensure ~/.aws dir exists
  file:
    path: "~/.aws"
    state: directory
  become: yes
  become_user: "{{ awscli_user }}"

- name: Create credentials file
  template: src="credentials.j2"
            dest="~/.aws/credentials"
  with_dict: wordpress_sites
  become: yes
  become_user: "{{ awscli_user }}"